name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t odagora/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true odagora/react-test npm test

      - run: docker build -t odagora/multi-client ./client
      - run: docker build -t odagora/multi-nginx ./nginx
      - run: docker build -t odagora/multi-server ./server
      - run: docker build -t odagora/multi-worker ./worker

      - run: docker push odagora/multi-client
      - run: docker push odagora/multi-nginx
      - run: docker push odagora/multi-server
      - run: docker push odagora/multi-worker
